name: shell commands 

on:
  - push

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Set Terraform 
        uses: harshicorp/setup-terraform@2
        with:
           terraform_version: 1.4.2
           continue-on=error: true
      - name: Terraform init
        run: terraform init
      - name: echo string
        run: echo "Hello"
      - name: Multi line string
        run: |
          pwd
          node -v
          ls -a
      